### ISSUE TITLE
content wider than screen

### ISSUE THREAD

**Issue by tianheg** [tianheg/blog#10]
Error page:

![image](https://user-images.githubusercontent.com/52186032/103470996-43645400-4db5-11eb-8135-97dfe6a37a5c.png)

**Comment by tianheg** [comment]
code display problem

**Comment by tianheg** [comment]
modify `~/config.toml`:

```toml
[markup.highlight]
        codeFences = true
        guessSyntax = false
        lineNos = true
        lineNumbersInTable = true --> false
        noClasses = false --> true
```

now display:
![image](https://user-images.githubusercontent.com/52186032/103471266-292c7500-4db9-11eb-9703-012ef87c7a62.png)
