### ISSUE TITLE
beautify my code display

### ISSUE THREAD

**Issue by tianheg** [tianheg/blog#44]
alternative: perldoc tango emacs friendly, from https://help.farbox.com/pygments.html .

Seting:

```toml
# Markdown renderer
[markup]
    [markup.highlight]
        style = "perldoc" # alternative: perldoc tango emacs friendly
```

Seems great: https://blog.yidajiabei.xyz/posts/create-cool-github-profile/
